apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'severity', 'component', 'name']
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 4h
      receiver: telegram
      routes:
        - matchers:
            - component = 'monitoring'
          receiver: telegram
          group_wait: 0s
          repeat_interval: 30m

        - matchers:
            - severity = 'critical'
          receiver: telegram
          group_wait: 1s
          repeat_interval: 1h

    receivers:
      - name: telegram
        telegram_configs:
        - bot_token_file: '/run/secrets/telegram_token'
          chat_id_file: '/run/secrets/telegram_chat_id'
          message: |
            {{ if eq .Status "firing" }}🔥 АЛЕРТ{{ else }}✅ РЕШЕНО{{ end }}

            Алерт: {{ .GroupLabels.alertname }}
            Срочность: {{ .CommonLabels.severity }}
            Компонент: {{ .CommonLabels.component }}

            {{ range .Alerts }}
            {{ if .Labels.name }}📦 Контейнер: {{ .Labels.name }}{{ end }}
            {{ if .Labels.instance }}🖥 Хост: {{ .Labels.instance }}{{ end }}
            📝 {{ .Annotations.description }}
            ⏰ Начало: {{ .StartsAt.Local.Format "02.01.2006 15:04:05" }}
            {{ end }}     
          # parse_mode=""
          parse_mode: ""
          send_resolved: true

    inhibit_rules:
      - source_matchers:
          - alertname = "CAdvisorDown"
        target_matchers:
          - component = "container"
        equal: []

      - source_matchers:
          - alertname = "NodeExporterDown"
        target_matchers:
          - component = "host"
        equal: []

      - source_matchers:
          - severity = "critical"
        target_matchers:
          - severity = "warning"
        equal: ['alertname', 'component', 'name']
