apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: monitoring
  labels:
    app.kubernetes.io/name: adminer
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/version: "4.8.1"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: adminer
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: monitoring
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
